Update lean_action_ci

diff --git a/.github/workflows/lean_action_ci.yml b/.github/workflows/lean_action_ci.yml
--- a/.github/workflows/lean_action_ci.yml
+++ b/.github/workflows/lean_action_ci.yml
@@ -13,4 +13,9 @@ jobs:
       - uses: actions/checkout@v5
       - uses: leanprover/lean-action@v1
       - name: Check Axioms
-        run: lake exe check_axioms
+        run: |
+          lake exe check_axioms
+          if [ $? -ne 0 ]; then
+            echo "Axiom check failed!"
+            exit 1
+          fi
